const allProducts = [
    // Indoor Plants
    { id: 1, name: 'Fiddle Leaf Fig', price: 29.99, tag: 'NEW ARRIVAL', image: 'fiddle.png', description: ['A beautiful indoor plant known for its large, violin-shaped leaves.'], reviews: ['Beautiful leaves!'], category: 'indoor', page: 'indoor1.html' },
    { id: 3, name: 'Snake Plant', price: 89.99, tag: 'BEST SELLER', image: 'snake.png', description: 'The snake plant is a resilient low-maintenance plant with tall upright leaves and striking patterns ideal for adding greenery with minimal care.', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },
    { id: 4, name: 'Spider Plant', price: 34.99, tag: 'POPULAR', image: 'spider.png', description: 'The spider plant is a lively low-maintenance houseplant with arching green leaves and playful white-striped offsets making it a charming and easy-to-care-for addition to any home', reviews:['Light: Bright, indirect light is best. Too much direct sunlight can scorch the leaves.', 'Water: Keep the soil slightly moist. Water when the top inch of soil feels dry.','Humidity: Spider plants like humidity but can tolerate average household levels.','Temperature: They prefer temperatures between 65-75°F (18-24°C).'], category: 'indoor', page: 'indoor1.html' }, // Corrected line
    { id: 5, name: 'Peace Lily', price: 120.99, tag: 'NEW ARRIVAL', image: 'peace.png', description: 'The peace lily is a graceful plant with glossy green leaves and elegant white blooms that thrive in low light and add a touch of serenity to any indoor space.', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },
    { id: 6, name: 'Aloe Vera', price: 17.99, tag: '90% OFF', image: 'aloe.png', description: 'Aloe vera is a succulent plant with thick fleshy leaves that contain a soothing gel used for its healing properties and requires minimal care.', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },
    { id: 7, name: 'ZZ Plant', price: 222.99, tag: 'POPULAR', image: 'zz.png', description: 'The ZZ plant is a robust and low-maintenance houseplant with glossy, dark green leaves that thrives in low light and infrequent watering.', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },
    { id: 8, name: 'Rubber Plant', price: 27.99, tag: '75% OFF', image: 'rubber.png', description: 'Has large, glossy leaves, a popular choice for its air-purifying qualities.', reviews: ['Shiny leaves!', 'Easy to grow!'], category: 'indoor', page: 'indoor1.html' },
    { id: 31, name: 'Boston Fern', price: 128.99, tag: 'CLASSIC', image: 'bost.jpg', description: 'The Boston fern is a lush and feathery plant with delicate, arching fronds that thrives in humidity and adds a touch of classic greenery to indoor environments.', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },
    { id: 32, name: 'Money Plant', price: 79.99, tag: 'GOOD LUCK', image: 'mone.jpeg', description: 'The money plant is a hardy and adaptable vine with heart-shaped leaves that is often grown for its easy care and believed to bring good fortune and prosperity.', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },
    { id: 33, name: 'Philodendron', price: 79.99, tag: 'VERSATILE', image: 'philo.jpg', description: 'The Philodendron is a versatile and low-maintenance plant with heart-shaped leaves that adds lush greenery to indoor spaces and adapts well to various light conditions..', reviews: ['Light: Thrives in low to bright indirect light. Tolerates some direct sunlight.', 'Water: Water sparingly; allow the soil to dry out completely between waterings.','Humidity: Adaptable to a range of humidity levels.','Temperature: Prefers temperatures between 60-75°F (15-24°C).','Soil: Use a well-draining potting mix, like a cactus or succulent mix'], category: 'indoor', page: 'indoor1.html' },

    

    // Leafy Plants
    { id: 2, name: 'Monstera Delica', price: 34.99, tag: '50% OFF', image: 'mon.png', description: 'Known for its large leaves with natural splits and holes, popular for its unique appearance.', reviews: ['Beautiful leaves!', 'Very healthy!'], category: 'leafy', page: 'leafy1.html' },
    { id: 23, name: 'Spinach', price: 29.99, tag: 'NUTRITIOUS', image: 'spin.jpeg', description: 'A common leafy green known for its high iron content and versatility in cooking.', reviews:['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.' ], category: 'leafy', page: 'leafy1.html' },
    { id: 24, name: 'Kale', price: 34.99, tag: 'SUPERFOOD', image: 'kali.jpg', description: 'A nutritious leafy green vegetable, rich in vitamins K, A, and C, with a slightly bitter taste.', reviews: ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},
    { id: 25, name: 'Lettuce ', price: 19.99, tag: 'CRISP', image: 'lett.jpg', description: 'A popular leafy green with a crisp texture and mild flavor, widely used in salads and sandwiches.', reviews:  ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},
    { id: 26, name: 'Swiss Chard', price: 14.99, tag: 'COLORFUL', image: 'swiss.jpg', description: 'A colorful leafy green with tender leaves and crisp stalks, often used in sautés and soups.', reviews:  ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},
    { id: 27, name: 'Collard Greens', price: 24.99, tag: 'HEARTY', image: 'coll.jpg', description: 'A hearty, nutritious leafy green popular in Southern cuisine, known for its distinct flavor.', reviews: ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},
    { id: 28, name: 'Mustard Greens', price: 12.99, tag: 'ZESTY', image: 'mus.jpeg', description: 'A pungent, peppery leafy green often used in stir-fries and salads, rich in vitamins.', reviews: ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},
    { id: 29, name:'Arugula', price: 22.99, tag: 'PEPPY', image: 'arg.jpg', description: 'A distinctive peppery-flavored leafy green, often used in salads and as a pizza topping.', reviews: ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},
    { id: 30, name: 'Beet Greens', price: 27.99, tag: 'EARTHY', image: 'beet.jpg', description: 'The leafy tops of beet plants, with a slightly earthy flavor, packed with vitamins and minerals.', reviews:  ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.','Provide Adequate Light: Ensure plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.','Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can harm plants.','Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.','Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'] , category: 'leafy', page: 'leafy1.html'},

    

    // Flowering Plants
    { id: 9, name: 'Rose', price: 18.99, tag: 'BEST SELLER', image: 'rose.png', description: 'Rose plants require a balanced fertilizer to promote healthy growth, blooming, and flowering.', reviews: ['Fertilize rose plants regularly', 'They are heavy feeders'], category: 'flowering', page: 'flower1.html' },
    { id: 10, name: 'Marigold', price: 26.99, tag: 'NEW ARRIVAL', image: 'flo.png', description: 'Marigold plants are relatively easy to care for and can thrive in a variety of conditions. ', reviews: ['Soil pH: Marigold plants prefer slightly acidic to neutral soil', 'Soil type: Well-draining soil with organic matter', 'Avoid overfertilizing, as this can lead to weak growth and fewer blooms'], category: 'flowering', page: 'flower1.html' },
    { id: 42, name: 'Sunflower', price: 890.99, tag: 'BRIGHT', image: 'sun.png', description: 'Sunflowers are tall, vibrant flowers known for their large heads that track the sun. They are popular for their beauty and edible seeds.', reviews: ['Light: Full sun (6-8 hours daily) is essential.', 'Water: Require regular watering, especially when young.', 'Soil: Well-drained, fertile soil.', 'Care: Support tall varieties to prevent bending.'], category: 'flowering', page: 'flower1.html' },
    { id: 43, name: 'Daisy', price: 170.99, tag: 'CHEERFUL', image: 'daisy.jpg', description: 'Daisies are cheerful and common flowering plants with distinctive white petals and a yellow center, symbolizing innocence and purity.', reviews: ['Light: Full sun to partial shade.', 'Water: Keep soil moist but well-drained.', 'Soil: Adaptable to various soil types.', 'Care: Deadhead spent blooms for continuous flowering.'], category: 'flowering', page: 'flower1.html' },
    { id: 44, name: 'Lavender', price: 128.99, tag: 'FRAGRANT', image: 'lav2.jpeg', description: 'Lavender is a fragrant, purple-flowered herb known for its calming aroma and use in essential oils, culinary dishes, and ornamental gardens.', reviews: ['Light: Requires full sun.', 'Water: Drought-tolerant once established; avoid overwatering.', 'Soil: Well-drained, sandy soil.', 'Care: Prune after flowering to maintain shape.'], category: 'flowering', page: 'flower1.html' },
    { id: 45, name: 'Iris', price: 796.99, tag: 'ELEGANT', image: 'iris.png', description: 'Irises are striking flowering plants known for their elegant, often ruffled petals and wide range of colors. They are popular in perennial gardens.', reviews: ['Light: Full sun is preferred.', 'Water: Moderate watering; avoid waterlogging.', 'Soil: Well-drained soil.', 'Care: Divide overcrowded rhizomes every few years.'], category: 'flowering', page: 'flower1.html' },
    { id: 46, name: 'Tulip', price: 222.99, tag: 'SPRING', image: 'tulip.png', description: 'Tulips are iconic spring-blooming flowers known for their cup-shaped blooms and bright, varied colors. They grow from bulbs.', reviews: ['Light: Full sun is ideal.', 'Water: Keep soil moist during growth; less once dormant.', 'Soil: Well-drained soil.', 'Care: Plant bulbs in fall for spring blooms.'], category: 'flowering', page: 'flower1.html' },
    { id: 47, name: 'Orchid', price: 790.99, tag: 'EXOTIC', image: 'orchid.png', description: 'Orchids are exotic and beautiful flowering plants, prized for their unique and diverse flower shapes and vibrant colors. They often grow as epiphytes in nature.', reviews: ['Light: Bright, indirect light.', 'Water: Water when potting mix is almost dry.', 'Humidity: High humidity preferred.', 'Care: Use orchid-specific potting mix; fertilize regularly.'], category: 'flowering', page: 'flower1.html' },

    

    // Vegetable Saplings
    { id: 11, name: 'Tomato', price: 29.99, tag: 'JUICY', image: 'toma.png', description: 'A juicy red or yellow fruit commonly used in salads, sauces and soups.', reviews:['Water Consistently: Keep the soil evenly moist, but avoid waterlogging. Water deeply and regularly, especially during dry spells.'], category: 'vegetable', page: 'veg.html' },
    { id: 12, 'name': 'Carrot', price: 34.99, tag: 'CRISP', image: 'car.jpg', description: 'Crisp orange root vegetables with a slightly sweet flavor.', reviews: ['Provide Adequate Light: Ensure vegetable plants receive enough sunlight, typically 6-8 hours a day, for optimal growth.'], category: 'vegetable', page: 'veg.html' },
    { id: 13, name: 'Lettuce ', price: 19.99, tag: 'SALAD STAPLE', image: 'lett.jpg', description: 'A leafy green vegetable known for its crisp texture and mild flavor.', reviews: ['Fertilize Wisely: Use appropriate fertilizers to provide essential nutrients, but avoid over-fertilizing, which can lead to weak growth and fewer blooms'], category: 'vegetable', page: 'veg.html' },
    { id: 14, name: 'Cucumber', price: 14.99, tag: 'REFRESHING', image: 'cucu.jpg', description: 'Crisp, refreshing green vegetables with a mild flavor and high water content.', reviews: ['Manage Pests: Monitor for pests and diseases regularly. Use organic or chemical controls as needed, and practice good garden hygiene.'], category: 'vegetable', page: 'veg.html' },
    { id: 15, name: 'Bell Pepper', price: 24.99, tag: 'COLORFUL', image: 'veg sap.jpeg', description: 'Colorful, crisp vegetables with a sweet flavor, rich in vitamins A and C.', reviews: ['Prune and Support: Trim excess foliage to improve air circulation and provide stakes or cages for plants that need support to grow upright.'], category: 'vegetable', page: 'veg.html' },
    { id: 16, name: 'Broccoli', price: 12.99, tag: 'NUTRIENT RICH', image: 'bro.jpg', description: 'A green vegetable with a tree-like structure and a slightly bitter taste.', reviews: ['Water Consistently: Keep the soil evenly moist, but avoid waterlogging.'], category: 'vegetable', page: 'veg.html' },
    { id: 17, name: 'Cauliflower', price: 22.99, tag: 'VERSATILE', image: 'cauli.jpeg', description: 'A versatile white vegetable with a mild flavor and a dense, fibrous texture.', reviews: ['Provide Adequate Light: Ensure vegetable plants receive enough sunlight.'], category: 'vegetable', page: 'veg.html' },
    { id: 18, name: 'Zucchini', price: 27.99, tag: 'REFRESHER', image: 'zu.jpeg', description: 'A green summer squash with a mild flavor and tender texture.', reviews: ['Fertilize Wisely: Use appropriate fertilizers.'], category: 'vegetable', page: 'veg.html' },

    

  // Bonsai Plants
{ id: 48, name: 'Ficus ', price: 400.99, tag: 'AERIAL', image: 'ficus.png', description: 'The Ficus bonsai is known for its aerial roots and graceful trunk, making it a popular choice for indoor cultivation. It is relatively easy to care for and adaptable to various conditions.', reviews: ['Light: Bright, indirect light is best. Too much direct sunlight can scorch the leaves.', 'Water: Keep the soil slightly moist. Water when the top inch of soil feels dry.', 'Humidity: Ficus bonsai like humidity but can tolerate average household levels.', 'Temperature: They prefer temperatures between 65-75°F (18-24°C).'], category: 'bonsai', page: 'bonsai1.html' },
{ id: 49, name: 'Maple ', price: 170.99, tag: 'AUTUMN', image: 'map.png', description: 'Maple bonsai are celebrated for their vibrant autumn foliage and delicate branch structure. They are deciduous and require seasonal care, making them a stunning addition to any collection.', reviews: ['Light: Prefers partial shade, especially during hot summer afternoons.', 'Water: Keep soil consistently moist; do not let it dry out completely.', 'Humidity: Appreciates higher humidity; consider misting or a humidity tray.', 'Temperature: Best in temperate climates, protect from severe frost.', 'Soil: Well-draining, moisture-retentive bonsai soil.'], category: 'bonsai', page: 'bonsai1.html' },
{ id: 50, name: 'Chinese Elm ', price: 128.99, tag: 'EASY CARE', image: 'elm.png', description: 'The Chinese Elm bonsai is highly popular for its resilience, fine branching, and attractive bark. It’s an excellent choice for beginners due to its forgiving nature and rapid growth.', reviews: ['Light: Adapts to full sun to partial shade; prefers bright, indirect light indoors.', 'Water: Water when the top inch of soil is dry; do not let it dry out completely.', 'Humidity: Tolerates average household humidity but benefits from higher levels.', 'Temperature: Hardy outdoors, can be kept indoors with proper light and care.', 'Soil: Standard bonsai soil mix.'], category: 'bonsai', page: 'bonsai1.html' },
{ id: 51, name: 'Jade Plant ', price: 796.99, tag: 'DROUGHT', image: 'jade.png', description: 'The Jade Plant bonsai is a succulent, known for its thick, fleshy leaves and sturdy trunk. It is remarkably drought-tolerant and easy to care for, making it a favorite for beginners.', reviews: ['Light: Prefers bright, indirect light; can tolerate some direct sun.', 'Water: Water sparingly; allow soil to dry out completely between waterings.', 'Humidity: Very adaptable to low humidity.', 'Temperature: Prefers warm temperatures; avoid frost.', 'Soil: Well-draining cactus or succulent mix.'], category: 'bonsai', page: 'bonsai1.html' },
{ id: 52, name: 'Bougainvillea ', price: 222.99, tag: 'VIBRANT', image: 'bou.jpg', description: 'Bougainvillea bonsai are prized for their spectacular, vibrant bracts (often mistaken for flowers) that bloom profusely in warm climates. They require abundant sunlight and careful watering.', reviews: ['Light: Requires full sun to bloom prolifically.', 'Water: Allow soil to dry out slightly between waterings to encourage flowering.', 'Humidity: Tolerates various humidity levels.', 'Temperature: Prefers warm climates; protect from cold.', 'Soil: Well-draining potting mix.'], category: 'bonsai', page: 'bonsai1.html' },
{ id: 53, name: 'Azalea ', price: 790.99, tag: 'BLOOMS', image: 'azl.png', description: 'Azalea bonsai are famous for their stunning, profuse flowers in spring. They are acid-loving plants that require specific care to thrive, making them a beautiful challenge.', reviews: ['Light: Prefers partial shade, especially afternoon shade.', 'Water: Keep soil consistently moist; use acid water (rainwater or acidified tap water).', 'Humidity: Appreciates high humidity.', 'Temperature: Prefers cool temperatures; protect from extreme heat and frost.', 'Soil: Acidic, well-draining bonsai soil.'], category: 'bonsai', page: 'bonsai1.html' },
{ id: 54, name: 'Pine ', price: 120.99, tag: 'CLASSIC', image: 'pine.png', description: 'Pine bonsai are iconic for their stately presence and textured bark. They demand specific care, including precise pruning and wiring, making them a rewarding challenge for experienced enthusiasts.', reviews: ['Light: Needs full sun outdoors.', 'Water: Allow the soil to dry slightly between waterings.', 'Humidity: Tolerates a range of humidity, good air circulation is key.', 'Temperature: Hardy outdoor plant, protect from extreme cold.', 'Soil: Fast-draining bonsai soil mix.'], category: 'bonsai', page: 'bonsai1.html' },
    

    // Cactus Plants
  
    { id: 55, name: 'Prickly Pear ', price: 89.99, tag: 'UNIQUE', image: 'pr.jpeg', description: 'A resilient cactus known for its flat, paddle-like stems and edible fruit.', reviews: ['Full sun.', 'Well-draining soil.', 'Drought tolerant.'], category: 'cactus', page: 'Cactus1.html' },
    { id: 56, name: 'Barrel Cactus', price: 120.99, tag: 'STURDY', image: 'bar.jpg', description: 'A large, ribbed, barrel-shaped cactus often found in deserts.', reviews: ['Full sun.', 'Minimal water.', 'Needs good drainage.'], category: 'cactus', page: 'Cactus1.html' },
    { id: 57, name: 'Schlumbergera ', price: 17.99, tag: 'BLOOMER', image: 'sc.jpg', description: 'Often called Christmas Cactus, it blooms vibrant flowers in winter.', reviews: ['Bright, indirect light.', 'Water when top soil is dry.', 'High humidity prefers.'], category: 'cactus', page: 'Cactus1.html' },
    { id: 58, name: 'Easter Cactus', price: 12.99, tag: 'SPRING ', image: 'eas.jpg', description: 'Similar to Christmas Cactus, but blooms around Easter with star-shaped flowers.', reviews: ['Bright, indirect light.', 'Water when dry.', 'Cooler temps for blooming.'], category: 'cactus', page: 'Cactus1.html' },
    { id: 59, name: 'Golden Barrel ', price: 79.99, tag: 'GOLDEN ', image: 'gold.jpg', description: 'A spherical cactus covered in golden-yellow spines, a desert classic.', reviews: ['Full sun.', 'Drought tolerant.', 'Well-drained soil.'], category: 'cactus', page: 'Cactus1.html' },
    { id: 60, name: 'Bunny Ear ', price: 22.99, tag: 'ADORABLE', image: 'bun.jpg', description: 'A popular houseplant cactus with paddle-like segments resembling bunny ears.', reviews: ['Bright, direct sun.', 'Water sparingly.', 'Avoid overwatering.'], category: 'cactus', page: 'Cactus1.html' },
    { id: 61, name: 'Moon Cactus', price: 79.99, tag: 'COLORFUL ', image: 'moon.jpeg', description: 'A grafted cactus with a colorful top (gymnocalycium) and green base (hylocereus).', reviews: ['Bright, indirect light.', 'Water when dry.', 'Protect from direct sun.'], category: 'cactus', page: 'Cactus1.html' },


  

    // Herbal Plants
    { id: 34, name: 'Basil', price: 34.99, tag: 'AROMATIC', image: 'bas.png', description: 'The Basil plant is a popular aromatic herb used in culinary dishes. It prefers warm climates and well-drained soil.', reviews: ['Light: Needs at least 6 hours of direct sunlight daily.', 'Water: Keep soil consistently moist, but not waterlogged.', 'Humidity: Prefers moderate humidity.', 'Temperature: Best between 65-75°F (18-24°C).'], category: 'herb', page: 'herb1.html' },
    { id: 35, name: 'Mint', price: 89.99, tag: 'REFRESHING', image: 'min.png', description: 'Mint is a vigorous, fast-growing herb known for its refreshing aroma and flavor. It can spread aggressively, so consider planting in containers.', reviews: ['Light: Prefers partial shade to full sun.', 'Water: Keep soil consistently moist.', 'Humidity: Tolerates a wide range of humidity.', 'Temperature: Adaptable to various temperatures.'], category: 'herb', page: 'herb1.html' },
    { id: 36, name: 'Rosemary', price: 120.99, tag: 'FRAGRANT', image: 'mar.png', description: 'Rosemary is a fragrant, evergreen herb with needle-like leaves, commonly used in cooking and aromatherapy. It thrives in sunny, dry conditions.', reviews: ['Light: Requires full sun (6-8 hours daily).', 'Water: Drought-tolerant once established; water sparingly.', 'Humidity: Prefers low to moderate humidity.', 'Temperature: Likes warm temperatures, but can tolerate some cold.'], category: 'herb', page: 'herb1.html' },
    { id: 37, name: 'Oregano', price: 17.99, tag: 'PUNGENT', image: 'org.png', description: 'Oregano is a pungent herb widely used in Mediterranean and Mexican cuisines. It is a hardy perennial that thrives in sunny, well-drained locations.', reviews: ['Light: Full sun is best.', 'Water: Allow soil to dry out between waterings.', 'Humidity: Tolerates various humidity levels.', 'Temperature: Prefers warm climates.'], category: 'herb', page: 'herb1.html' },
    { id: 38, name: 'Thyme', price: 128.99, tag: 'AROMATIC', image: 'thy.jpg', description: 'Thyme is a low-growing, aromatic herb with small, fragrant leaves, excellent for seasoning. It is drought-tolerant and thrives in full sun.', reviews: ['Light: Full sun (at least 6 hours daily).', 'Water: Water sparingly; prefers dry conditions.', 'Humidity: Low to moderate humidity.', 'Temperature: Hardy in various temperatures, prefers warmth.'], category: 'herb', page: 'herb1.html' },
    { id: 39, name: 'Parsley', price: 79.99, tag: 'GARNISH', image: 'par.jpeg', description: 'Parsley is a widely used fresh herb for garnishing and flavoring. It is rich in vitamins and antioxidants and prefers moist, well-drained soil.', reviews: ['Light: Partial shade to full sun.', 'Water: Keep soil consistently moist.', 'Humidity: Prefers moderate humidity.', 'Temperature: Best in cooler temperatures, tolerates some heat.'], category: 'herb', page: 'herb1.html' },
    { id: 40, name: 'Chives', price: 222.99, tag: 'MILD ONION', image: 'chi.jpeg', description: 'Chives are slender, hollow-leaved herbs with a mild onion-like flavor, often used as a garnish. They are easy to grow and relatively low-maintenance.', reviews: ['Light: Full sun to partial shade.', 'Water: Keep soil consistently moist.', 'Humidity: Adaptable.', 'Temperature: Hardy and prefers cooler temperatures.'], category: 'herb', page: 'herb1.html' },
    { id: 41, name: 'Cilantro', price: 79.99, tag: 'CITRUSY', image: 'cil.jpg', description: 'Cilantro (coriander leaves) is an aromatic herb with a distinctive fresh, citrusy flavor, essential in many cuisines. It tends to bolt in hot weather.', reviews: ['Light: Partial shade; can tolerate full sun in cooler climates.', 'Water: Keep soil consistently moist.', 'Humidity: Moderate humidity.', 'Temperature: Prefers cool temperatures; prone to bolting in heat.'], category: 'herb', page: 'herb1.html' },
];